export const brandCountries: Record<string, string> = {
  Acura: "Japan",
  Alfa: "Italy",
  "Alfa Romeo": "Italy",
  Aston: "United Kingdom",
  Audi: "Germany",
  Bentley: "United Kingdom",
  BMW: "Germany",
  Buick: "United States",
  Cadillac: "United States",
  Chevrolet: "United States",
  Chrysler: "United States",
  Dodge: "United States",
  Ferrari: "Italy",
  FIAT: "Italy",
  Ford: "United States",
  Genesis: "South Korea",
  GMC: "United States",
  Honda: "Japan",
  Hyundai: "South Korea",
  INFINITI: "Japan",
  Jaguar: "United Kingdom",
  Jeep: "United States",
  Kia: "South Korea",
  Lamborghini: "Italy",
  Land: "United Kingdom",
  "Land Rover": "United Kingdom",
  Lexus: "Japan",
  Lincoln: "United States",
  Maserati: "Italy",
  Mazda: "Japan",
  "Mercedes-Benz": "Germany",
  MINI: "United Kingdom",
  Mitsubishi: "Japan",
  Nissan: "Japan",
  Porsche: "Germany",
  Ram: "United States",
  Subaru: "Japan",
  Tesla: "United States",
  Toyota: "Japan",
  Volkswagen: "Germany",
  Volvo: "Sweden"
};

export const bodyRules: Array<[RegExp, string]> = [
  [/\b(f-?150|silverado|sierra|ram 1500|tacoma|tundra|ranger|colorado|canyon|frontier|ridgeline)\b/i, "truck"],
  [/\b(wrangler|bronco|4runner|land cruiser|defender)\b/i, "suv"],
  [/\b(escalade|suburban|tahoe|yukon|expedition|pilot|highlander|rav4|cr-v|crv|venza|x3|x5|q3|q5|q7|gle|glc|rx|mdx|rdx|explorer|escape|edge|rogue|murano|pathfinder|forester|outback|crosstrek|sorento|sportage|telluride|palisade|kona|tucson|santa fe|seltos|cx-3|cx-30|cx-5|cx-50|cx-9|hr-v|hrv|passport)\b/i, "suv"],
  [/\b(corvette|mustang|camaro|challenger|911|boxster|cayman|miata|mx-5|supra|brz|gr86|gr 86|rc|lc)\b/i, "coupe"],
  [/\b(convertible|cabriolet|roadster|spyder)\b/i, "convertible"],
  [/\b(van|sienna|odyssey|pacifica|transit|sprinter|express)\b/i, "van"],
  [/\b(wagon|allroad|sportwagen)\b/i, "wagon"],
  [/\b(hatch|golf|fit|leaf|prius|ioniq)\b/i, "hatchback"],
  [/\b(civic|accord|camry|corolla|altima|sentra|maxima|malibu|impala|charger|fusion|focus|elantra|sonata|optima|k5|a3|a4|a6|3 series|5 series|c-class|e-class|is|es|tlx|ilx)\b/i, "sedan"]
];
